export default [
  { weight: 1, value: { scale: 4, url: '/assets/textures/metal_floor_3.jpg' }},
  
  { weight: 5, value: { scale: 8, url: '/assets/textures/metal_door_3.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/metal_panel.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/iron_panel.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/iron_panel_2.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/rust_panel.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/corrugated.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/circuit_board_2.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/circuit_board_3.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_2.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_floor_1.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_floor_3.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_3.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_4.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/pipes.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_5.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_7.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_8.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_9.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_10.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_wall_11.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_wall_12.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/pipes4.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_wall_13.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_wall_14.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/dark_panel.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/metal_floor_2.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/panel1.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/panel9.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_wall_14.jpg' }},

  { weight: 1, value: { scale: 12, url: '/assets/textures/scratched_metal.jpg' }},
]
