export default [
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_ceiling_1.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_ceiling_6.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_wall_13.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_floor_1.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_floor_2.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_floor_3.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_3.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_6.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_wall_13.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/roof1.jpg' }},
  { weight: 1, value: { scale: 4, url: '/assets/textures/circuit_board_2.jpg' }},
  { weight: 1, value: { scale: 4, url: '/assets/textures/concrete2.jpg' }},
  { weight: 1, value: { scale: 4, url: '/assets/textures/concrete4.jpg' }},
  { weight: 1, value: { scale: 4, url: '/assets/textures/terminal_floor_4.jpg' }},
  { weight: 1, value: { scale: 8, url: '/assets/textures/terminal_panel_8.jpg' }},
  { weight: 1, value: { scale: 4, url: '/assets/textures/terminal_wall_14.jpg' }},
]
